_BASE_: "base_prw.yaml"
MODEL:
  RESNETS:
    OUT_FEATURES: ["res3","res4","res5"]
    RES5_DILATION: 2
  ROI_HEADS:
    IN_FEATURES: ["res3","res4","res5"]
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        NUM_FEATURE_LEVELS: 3
  REID:
    MODEL:
      MS_WEIGHTS: [1.0,1.0,1.0]
OUTPUT_DIR: "outputs/ddtps/ddtps_prw_ms_d16"