_BASE_: "base.yaml"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
SOLVER:
  MAX_ITER: 71300 # 1426 * 50
  STEPS: (54188,65596)
  CHECKPOINT_PERIOD: 2852
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", "PRW_Query",) #
TEST:
  EVAL_PERIOD: 2852
OUTPUT_DIR: "outputs/ddtps/ddtps_prw"