_BASE_: "base.yaml"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
SOLVER:
  MAX_ITER: 140050 # 2801 * 50
  STEPS: (106438,)
  CHECKPOINT_PERIOD: 5602
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", "CUHK-SYSU_TestG100",) #
TEST:
  EVAL_PERIOD: 5602
OUTPUT_DIR: "outputs/ddtps/ddtps_cuhk"