_BASE_: "clip_detr_baseline.yaml"
MODEL:
   META_ARCHITECTURE: "ClipQueryGroundingBiAlign"
PERSON_SEARCH:
  REID:
    ROI_POOLER:
      TYPE: "ROIAlignV2"
      POOLER_RESOLUTION: [12,4]
      SAMP_RATIO: 2
      SCALES: [0.03125] # 1/32
    BOX_AUGMENTATION:
      ENABLE: True
      NAME: "dn_detr"
      H_CENTER: 0.4
      H_SCALE: 0.2
      NUM_LABELED: 3
      APPEND_GT: True
      NUM_UNLABLED: 3
SOLVER:
  MAX_ITER: 57000 # 570 * 100
  STEPS: (34200,) # 570 * 60
  CHECKPOINT_PERIOD: 570
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 10
  LR_FACTORS: [5.0,5.0,5.0,5.0]
  LR_GROUP_REGEX: ["grounding_trans.+","bbox_embed.+","conf_embed.+","query_embed.+"]
DATASETS:
  TRAIN: ("PRW_TBPS_Train",) 
  # TEST: ("PRW_TBPS_Query_QG","PRW_TBPS_Gallery_QG",)
TEST:
  EVAL_PERIOD: 60000
OUTPUT_DIR: "outputs/query_gd/clip_detr_bialign_seed_prw"
SEED: 58216138