_BASE_: "clip_detr_baseline.yaml"
MODEL:
  META_ARCHITECTURE: "ClipQueryGrounding8Deform"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
SOLVER:
  MAX_ITER: 140100 # 1401 * 100
  STEPS: (84060,)
  CHECKPOINT_PERIOD: 2802
  WARMUP_ITERS: 2802
  IMS_PER_BATCH: 8
  LR_FACTORS: [5.0,5.0,5.0,5.0]
  LR_GROUP_REGEX: ["grounding_trans.+","bbox_embed.+","conf_embed.+","query_embed.+"]
DATASETS:
  TRAIN: ("CUHK-SYSU_TBPS_Train",) 
  # TEST: ("CUHK-SYSU_TBPS_Query_QG","CUHK-SYSU_TBPS_Gallery_QG",)
TEST:
  EVAL_PERIOD: 160000
OUTPUT_DIR: "outputs/query_gd/clip_8deform_seed_cuhk"
SEED: 58216138