MODEL:
  META_ARCHITECTURE: "ClipQueryGroundingBaseline"
  WEIGHTS: ""
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
PERSON_SEARCH:
  DET:
    CLIP:
      NAME: "RN50"
      IMG_SIZE: [224,224] # pretrain image size
      STRIDE: 16
      FREEZE_AT_STAGE2: True
      FROZEN_BN: True
  REID:
    MODEL:
      EMB_DIM: 1024
      BN_NECK: False
    LOSS:
      OIM:
        LB_LAYER: "lb_norm"
        ULB_LAYER: "ulb_full"
        LB_FACTOR: 10
        ULB_FACTOR: 10
        NUM_LB: 483
        LEN_ULB: 500
        FEAT_DIM: 1024
        NORM_FEAT: True
        SYNC_MEMORY: False
        USE_FOCAL: True
        FOCAL_ALPHA: 1.0
        FOCAL_GAMMA: 2.0
        LOSS_WEIGHT: 1.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 900)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32

DATALOADER:
  NUM_WORKERS: 8
  ASPECT_RATIO_GROUPING: True

SOLVER:
  OPTIM: "Adam"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 0.00001
  WEIGHT_DECAY: 1.0e-4
  GAMMA: 0.1
  IMS_PER_BATCH: 6

TEST:
  IMS_PER_PROC: 5
# SEED: 42
VIS_PERIOD: 500
VERSION: 2