_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleGTInfer"
  # WEIGHTS: "outputs/oim_clip/def/oim_simple_detboxaug_coattmaskhigh_coattoptxidmix_oimshare_sdm_prw_30_slr_open_b10_plr_tdrop_mask02_mix03_cws/model_0011399.pth"
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
DATASETS:
  TEST: ("PRW_TBPS_Train",)
OUTPUT_DIR: "outputs/oim_clip/def/gtinfer_clip_re"