_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VidtPromptPDWithNeck"
PERSON_SEARCH:
  DET:
    MODEL:
      BOX_REFINE: True
      NECK:
        NHEADS: 8
        NUM_DEC_LAYERS: 6
        DIM_FEEDFORWARD: 1024
        DROPOUT: 0.1
        NUM_FEATURE_LEVELS: 4
        DEC_N_POINTS: 4
    LOSS:
      DEEP_SUPERVISION: True
      WEIGHTS:
        CLS: 2.0
        GIOU: 2.0
        L1: 5.0
        NO_OBJECT: 0.1
      FOCAL:
        ENABLE: True
        ALPHA: 0.25
        GAMMA: 2.0
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (632880,)
  BASE_LR: 5.0e-6 
  MAX_ITER: 791100 # 15822 * 50
  CHECKPOINT_PERIOD: 15822
  GAMMA: 0.1
  EPOCH_ITERS: 15822
  IMS_PER_BATCH: 5
DATASETS:
  TRAIN: ("COCO-CH",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",) #
TEST:
  EVAL_PERIOD: 31644
  DETECTION_SCORE_TS: [0.2,0.3]
OUTPUT_DIR: "outputs/vidt_ps/vidt-neck_prompt_pd_cococh_slr"