_BASE_: "base.yaml"
SOLVER:
  MAX_ITER: 213900 # 1426 * 150
  CHECKPOINT_PERIOD: 2852
  EPOCH_ITERS: 1426
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery",) #
TEST:
  EVAL_PERIOD: 2852
OUTPUT_DIR: "outputs/vidt_ps/vidt_prompt_pd"