MODEL:
  META_ARCHITECTURE: "SwinF4PSReid"
  WEIGHTS: "Data/model_zoo/swin_rcnn_small_solider_d2.pkl"
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  BACKBONE:
    NAME: "build_patch_embed_ln"
  PATCH_EMBED:
    PRETRAIN_IMG_SIZE: [256,128]
    PATCH_SIZE: [4,4]
    EMBED_DIM: 96
  ROI_HEADS:
    IN_FEATURES: ["stage3"]
  ROI_BOX_HEAD:
      POOLER_RESOLUTION: [16, 8]
      POOLER_SAMPLING_RATIO: 2
      POOLER_TYPE: "ROIAlignV2"
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        DEPTH: [2,2,18,2]
        NHEAD: [3, 6, 12, 24]
        WIN_SIZE: 7
        MLP_RATIO: 4
        QKV_BIAS: True
        DROPOUT: 0.0
        DROP_PATH: 0.1
        ATTN_DROPOUT: 0.0
        SEMANTIC_WEIGHT: 0.6
        OUT_CHANNELS: 768
        WITH_CP: False
  REID:
    MODEL:
      BN_NECK: False
      IN_FEAT: "stage3"
    LOSS:
      OIM:
        LB_LAYER: "lb_norm"
        ULB_LAYER: "ulb_full"
        LB_FACTOR: 30
        ULB_FACTOR: 30
        NUM_LB: 483
        LEN_ULB: 500
        FEAT_DIM: 768
        NORM_FEAT: True
        SYNC_MEMORY: False
        USE_FOCAL: True
        FOCAL_ALPHA: 1.0
        FOCAL_GAMMA: 2.0
        LOSS_WEIGHT: 1.0
    BOX_AUGMENTATION:
      NAME: "dn_detr"
      H_CENTER: 0.4
      H_SCALE: 0.2
      NUM_LABELED: 0
      APPEND_GT: True
      NUM_UNLABLED: 0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32

DATALOADER:
  NUM_WORKERS: 8
  ASPECT_RATIO_GROUPING: True

SOLVER:
  OPTIM: "SGD"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  WARMUP_ITERS: 0
  BASE_LR: 0.001
  WEIGHT_DECAY: 5.0e-4
  GAMMA: 0.1
  IMS_PER_BATCH: 4

TEST:
  IMS_PER_PROC: 8
# SEED: 42
VIS_PERIOD: 1000
VERSION: 2