_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "SwinF4PSReidFrozen"
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        SEMANTIC_WEIGHT: 0.2
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery","PRW_Query") #
OUTPUT_DIR: "outputs/swin_ps_reid/swin-small-frozen_prw_sem02"