_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "SwinF4PSReidFrozen"
  WEIGHTS: "Data/model_zoo/swin_base_patch4_window7_224_22k_d2.pkl"
  PATCH_EMBED:
    EMBED_DIM: 128
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        NHEAD: [4, 8, 16, 32]
        OUT_CHANNELS: 1024
        SEMANTIC_WEIGHT: 0.0
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery","PRW_Query") #
OUTPUT_DIR: "outputs/swin_ps_reid/swin-baseign-frozen_prw"