_BASE_: "prompt_small-ign_prw.yaml"
PERSON_SEARCH:
  PROMPT:
    STAGE_WISE: True
    PROMPT_START_STAGE: 1
    NUM_PROMPTS: [0,0,0,32]
    PROMPT_TYPE: "Fixed"
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery","CUHK-SYSU_TestG100") #
SOLVER:
  OPTIM: "Adam"
  BASE_LR: 0.0003
  STEPS: (33624,67248)
  MAX_ITER: 70050 # 1401 * 50
  CHECKPOINT_PERIOD: 2802
TEST:
  EVAL_PERIOD: 2802
OUTPUT_DIR: "outputs/swin_ps_reid/swin-small-ign-prompt32_cuhk_adam_headp"