_BASE_: "prompt_small_prw.yaml"
MODEL:
  WEIGHTS: "Data/model_zoo/swin_small_patch4_window7_224_22k_d2.pkl"
PERSON_SEARCH:
  QUERY_ENCODER_WEIGHTS: "Data/model_zoo/swin_small_patch4_window7_224_22k_d2.pkl"
SOLVER:
  STEPS: (25668,)
  BASE_LR: 0.001
  MAX_ITER: 35650 # 713 * 50
  CHECKPOINT_PERIOD: 1426
  GAMMA: 0.1
  IMS_PER_BATCH: 8
OUTPUT_DIR: "outputs/swin_ps_reid/swin-small-ign-prompt32_prw"