_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "SwinExtracter"
  WEIGHTS: ""
PERSON_SEARCH:
  QUERY_ENCODER_WEIGHTS: "Data/model_zoo/swin_small_patch4_window7_224_22k_d2.pkl"
  DET:
    MODEL:
      TRANSFORMER:
        SEMANTIC_WEIGHT: -1
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("MovieNet_Train_app10",) # "PRW_Query", "CUHK-SYSU_Gallery"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 240
  MAX_SIZE_TEST: 720
SOLVER:
  STEPS: (17112,34224)
  BASE_LR: 0.001
  MAX_ITER: 35650 # 713 * 50
  CHECKPOINT_PERIOD: 1426
  GAMMA: 0.1
  IMS_PER_BATCH: 8
TEST:
  IMS_PER_PROC: 1
  EVAL_PERIOD: 1426
OUTPUT_DIR: "outputs/swin_ps_reid/swin-small-ign_imgfeats"