MODEL:
  META_ARCHITECTURE: "SwinS3SimFPN"
  WEIGHTS: "Data/model_zoo/swin_base_patch4_window7_224_22k_d2.pkl"
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  BACKBONE:
    NAME: "build_patch_embed_ln"
  PATCH_EMBED:
    PRETRAIN_IMG_SIZE: [224,224]
    PATCH_SIZE: [4,4]
    EMBED_DIM: 128
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[32], [64], [128], [256], [512]] # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    HEAD_NAME: "StandardRPNHead" 
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    IOU_THRESHOLDS: [0.3, 0.7]
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
    PRE_NMS_TOPK_TRAIN: 2000 # Per FPN level
    PRE_NMS_TOPK_TEST: 1000 # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 300
    CONV_DIMS: [-1,-1]
    NMS_THRESH: 0.7
  ROI_HEADS:
    NAME: "StandardROIHeads" 
    NUM_CLASSES: 1
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    IOU_THRESHOLDS: [0.5]
    IOU_LABELS: [0, 1]
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
    SCORE_THRESH_TEST: 0.5
    NMS_THRESH_TEST: 0.4
    PROPOSAL_APPEND_GT: True
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1
    FC_DIM: 1024
    NUM_CONV: 4
    CONV_DIM: 256
    NORM: LN
    BBOX_REG_LOSS_TYPE: "smooth_l1"
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: [10.0, 10.0, 5.0, 5.0]
    SMOOTH_L1_BETA: 0.0
    POOLER_RESOLUTION: [14, 14]
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: "ROIAlignV2"
PERSON_SEARCH:
  DET:
    NUM_CLASSES: 1
    MODEL:
      TRANSFORMER:
        DEPTH: [2,2,18,2]
        NHEAD: [4, 8, 16, 32]
        WIN_SIZE: [7,7,7,7]
        MLP_RATIO: 4
        QKV_BIAS: True
        DROPOUT: 0.0
        DROP_PATH: 0.0
        ATTN_DROPOUT: 0.0
        SEMANTIC_WEIGHT: -1
        OUT_CHANNELS: 1024
        WITH_CP: False
      SIM_FPN:
        IN_FEATURE: "stage3"
        OUT_CHANNELS: 256
        SCALE_FACTORS: [4.0, 2.0, 1.0, 0.5]
  REID:
    ID_ASSIGN:
      NAME: "det"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 900)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32

DATALOADER:
  NUM_WORKERS: 8
  ASPECT_RATIO_GROUPING: True

SOLVER:
  OPTIM: "AdamW"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  WARMUP_ITERS: 1000
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.01
  STEPS: (98900,197800)
  MAX_ITER: 247250 # 4945 * 50
  CHECKPOINT_PERIOD: 9890
  GAMMA: 0.1
  IMS_PER_BATCH: 16

DATASETS:
  TRAIN: ("COCO-CH",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery","MovieNet_GalleryTestG2000",)

TEST:
  IMS_PER_PROC: 8
  EVAL_PERIOD: 9890
  DETECTIONS_PER_IMAGE: 100
  DETECTION_SCORE_TS: [0.5,]
# SEED: 42
VIS_PERIOD: 1000
VERSION: 2