_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleDetboxaugOimshareSdm"
  # WEIGHTS: "outputs/oim_clip/oim_simple_bi_cuhk_30_slr_open/model_0013075.pth"
  #ROI_HEADS:
  #  IOU_THRESHOLDS: [0.5]
  #  IOU_LABELS: [0, 1]
  #ROI_BOX_HEAD:
  #  SMOOTH_L1_BETA: 1.0
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
      TEXT_DROPOUT: 0.05
  REID:
    BOX_AUGMENTATION:
      NAME: "dn_detr"
      H_CENTER: 0.4
      H_SCALE: 0.2
      NUM_LABELED: 4
      APPEND_GT: False
      NUM_UNLABLED: 4
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
        LB_FACTOR: 30
        ULB_FACTOR: 30
    CWS: False
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 35872 # 1121 * 32
  STEPS: (11210,)
  CHECKPOINT_PERIOD: 2242
  WARMUP_ITERS: 1121
  IMS_PER_BATCH: 10
  LR_FACTORS: [10.0,10.0]
  LR_GROUP_REGEX: ["proposal_generator.+","roi_heads.box_predictor.+"]
  WEIGHT_DECAY_BIAS: 0.0
DATASETS:
  TRAIN: ("CUHK-SYSU_TBPS_Train",) 
  TEST: ("CUHK-SYSU_TBPS_Gallery", "CUHK-SYSU_TBPS_TestG100",)
TEST:
  EVAL_PERIOD: 1121
OUTPUT_DIR: "outputs/oim_clip/def/oim_simple_detboxaug_oimshare_sdm_cuhk_30_slr_open_b10_10det_tdrop_4box" #_seed"
# SEED: 58216138