_BASE_: "base.yaml"
MODEL:
  RESNETS:
    RES5_DILATION: 2
PERSON_SEARCH:
  REID:
    MODEL:
      TRANSFORMER:
        QUERY_AUX: True
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
INPUT:
  SIZE_DIVISIBILITY: 16
SOLVER:
  MAX_ITER: 112050 # 2241 * 20
  STEPS: (89640,)
  CHECKPOINT_PERIOD: 2241
  WARMUP_ITERS: 2241
  IMS_PER_BATCH: 5
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", "CUHK-SYSU_TestG100",) #
TEST:
  EVAL_PERIOD: 4482
OUTPUT_DIR: "outputs/dtps/dtps_cuhk_d16_qaux"