_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "DDTPS"
  RESNETS:
    RES5_DILATION: 2
PERSON_SEARCH:
  REID:
    MODEL:
      TRANSFORMER:
        QUERY_AUX: True
        QUERY_POS: False
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
INPUT:
  SIZE_DIVISIBILITY: 16
SOLVER:
  MAX_ITER: 57000 # 1140 * 20
  STEPS: (45600,)
  CHECKPOINT_PERIOD: 1140
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 5
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", "PRW_Query",) #
TEST:
  EVAL_PERIOD: 2280 
OUTPUT_DIR: "outputs/dtps/dtps_prw_d16_qaux_nqpos_dmap"