_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "SwinF4RCNNSeq"
SOLVER:
  STEPS: (118680,237360)
  BASE_LR: 0.001
  MAX_ITER: 247250 # 4945 * 50
  CHECKPOINT_PERIOD: 9890
  GAMMA: 0.1
  IMS_PER_BATCH: 16
DATASETS:
  TRAIN: ("COCO-CH",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",) #
TEST:
  EVAL_PERIOD: 9890
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/base-seq_cococh"