_BASE_: "base_prompts.yaml"
MODEL:
  META_ARCHITECTURE: "PrefixPromptedSwinF4RCNNPS"
  WEIGHTS: "Data/model_zoo/swin_rcnn_small_cococh_side.pkl"
PERSON_SEARCH:
  QUERY_ENCODER_WEIGHTS: "Data/model_zoo/swin_rcnn_small_solider_d2.pkl"
  PROMPT:
    PROMPT_START_STAGE: 1
    NUM_PROMPTS: 128
    POOL_SIZE: 20
    PROMPT_TYPE: "CODAPrompt"
    NUM_TASKS: 2
    CURRECT_TASK: 0
    LOSS_WEIGHT: 0.1
  REID:
    MODEL:
      IN_FEAT: "stage3"
      EMB_DIM: 768
      BN_NECK: False
    ID_ASSIGN:
      NAME: "det"
    LOSS:
      OIM:
        LB_LAYER: "lb_norm"
        ULB_LAYER: "ulb_full"
        LB_FACTOR: 30
        ULB_FACTOR: 30
        NUM_LB: 483
        LEN_ULB: 500
        FEAT_DIM: 768
        NORM_FEAT: True
        SYNC_MEMORY: False
        USE_FOCAL: True
        FOCAL_ALPHA: 1.0
        FOCAL_GAMMA: 2.0
        LOSS_WEIGHT: 0.5
SOLVER:
  STEPS: (22824,45648)
  BASE_LR: 0.001
  MAX_ITER: 47550 # 951 * 50
  CHECKPOINT_PERIOD: 1902
  GAMMA: 0.1
  IMS_PER_BATCH: 6
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 900)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery","PRW_Query",) #
TEST:
  IMS_PER_PROC: 6
  EVAL_PERIOD: 1902
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/coda-ps_prw"