_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VitPDWithLocal"
  WEIGHTS: ""

DATASETS:
  TRAIN: ("COCO-P_DINO",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",)

PERSON_SEARCH:
  DINO:
    NUM_LOCAL_TOKEN_GROUPS: 4
  DET:
    MODEL:
      TRANSFORMER:
        DEPTH: 8

SOLVER:
  MAX_ITER: 1602800
  OPTIM: "AdamW"
  LR_SCHEDULER_NAME: "WarmupCosineAfterWarmupLR"
  WARMUP_ITERS: 16028
  BASE_LR: 5.0e-4 # 5.0e-4
  IMS_PER_BATCH: 4
  EPOCH_ITERS: 16028
  CHECKPOINT_PERIOD: 16028
# SEED: 42
VIS_PERIOD: 1000
OUTPUT_DIR: "outputs/vit_ps_dino/vitpd-local_small-scratch"
VERSION: 2