_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VitPDWithLocal"

DATASETS:
  TRAIN: ("COCO-P_DINO",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",)

SOLVER:
  MAX_ITER: 1602800
  OPTIM: "AdamW"
  LR_SCHEDULER_NAME: "WarmupEpochBasedCosineLR"
  WARMUP_ITERS: 0
  BASE_LR: 1.0e-5
  IMS_PER_BATCH: 4
  COS_LR_MAX_FACTOR: 1.0
  COS_LR_MIN_FACTOR: 0.01
  EPOCH_ITERS: 16028
  CHECKPOINT_PERIOD: 16028
  CLIP_GRADIENTS:
    ENABLED: True
    FULL_MODEL: True
    CLIP_TYPE: "norm"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
# SEED: 42
VIS_PERIOD: 1000
OUTPUT_DIR: "outputs/vit_ps_dino/vitpd-local_small-coco_orgcfg"
VERSION: 2