_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VitPDWithLocalStochastic"

DATASETS:
  TRAIN: ("COCO-P_DINO_Stochastic",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",)
DATALOADER:
  NUM_WORKERS: 6
  ASPECT_RATIO_GROUPING: True
SOLVER:
  MAX_ITER: 133600
  OPTIM: "AdamW"
  LR_SCHEDULER_NAME: "WarmupEpochBasedCosineLR"
  WARMUP_ITERS: 0
  BASE_LR: 1.0e-5
  IMS_PER_BATCH: 24
  COS_LR_MAX_FACTOR: 1.0
  COS_LR_MIN_FACTOR: 0.01
  EPOCH_ITERS: 2672
  CHECKPOINT_PERIOD: 2672
  CLIP_GRADIENTS:
    ENABLED: True
    FULL_MODEL: True
    CLIP_TYPE: "norm"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
TEST:
  EVAL_PERIOD: 13360
# SEED: 42
VIS_PERIOD: 1000
OUTPUT_DIR: "outputs/vit_ps_dino/vitpd-local-stochastic_small-coco_orgcfg"
VERSION: 2