MODEL:
  META_ARCHITECTURE: "OimClip"
  WEIGHTS: ""
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[32, 64, 128, 256, 512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    HEAD_NAME: "StandardRPNHead" 
    IN_FEATURES: ["res4"]
    IOU_THRESHOLDS: [0.3, 0.7]
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
    PRE_NMS_TOPK_TRAIN: 12000
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 300
    NMS_THRESH: 0.7
  ROI_HEADS:
    NAME: "ClipRes5ROIHeadsPsNoStride"
    NUM_CLASSES: 1
    IN_FEATURES: ["res4"]
    IOU_THRESHOLDS: [0.1, 0.5]
    IOU_LABELS: [0, -1, 1]
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
    SCORE_THRESH_TEST: 0.5
    NMS_THRESH_TEST: 0.4
    PROPOSAL_APPEND_GT: True
  ROI_BOX_HEAD:
      NAME: "" 
      BBOX_REG_LOSS_TYPE: "smooth_l1"
      BBOX_REG_LOSS_WEIGHT: 10.0
      BBOX_REG_WEIGHTS: [10.0, 10.0, 5.0, 5.0]
      SMOOTH_L1_BETA: 0.111111 # 0.0
      POOLER_RESOLUTION: [16, 8]
      POOLER_SAMPLING_RATIO: 2
      POOLER_TYPE: "ROIAlignV2"
PERSON_SEARCH:
  DET:
    NUM_CLASSES: 1
    CLIP:
      NAME: "RN50"
      IMG_SIZE: [224,224] # pretrain image size
      STRIDE: 16
      FREEZE_AT_STAGE2: True
      FROZEN_BN: True
  REID:
    MODEL:
      EMB_DIM: 1024
      BN_NECK: False
    ID_ASSIGN:
      NAME: "det"
    LOSS:
      OIM:
        LB_LAYER: "lb_norm"
        ULB_LAYER: "ulb_full"
        LB_FACTOR: 10
        ULB_FACTOR: 10
        NUM_LB: 483
        LEN_ULB: 500
        FEAT_DIM: 1024
        NORM_FEAT: True
        SYNC_MEMORY: False
        USE_FOCAL: True
        FOCAL_ALPHA: 1.0
        FOCAL_GAMMA: 2.0
        LOSS_WEIGHT: 1.0
    CWS: False
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 900)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32

DATALOADER:
  NUM_WORKERS: 8
  ASPECT_RATIO_GROUPING: True

SOLVER:
  OPTIM: "Adam"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 0.00035
  WEIGHT_DECAY: 1.0e-4
  GAMMA: 0.1
  IMS_PER_BATCH: 6

TEST:
  IMS_PER_PROC: 5
  DETECTIONS_PER_IMAGE: 100
# SEED: 42
VIS_PERIOD: 500
VERSION: 2