_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleBiMHML2DFullyPred"
  # WEIGHTS: "outputs/oim_clip/oim_simple_bi_cuhk_30_slr_open/model_0013075.pth"
  #ROI_HEADS:
  #  IOU_THRESHOLDS: [0.5]
  #  IOU_LABELS: [0, 1]
  #ROI_BOX_HEAD:
  #  SMOOTH_L1_BETA: 1.0
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
  REID:
    MIM_RATIO: 0.5
    MIM_LOSS_W: 10
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.0001
  MAX_ITER: 20520 # 570 * 36
  STEPS: (9120,) # 570 * 16
  CHECKPOINT_PERIOD: 570
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 10
  LR_FACTORS: [5.0,5.0,5.0,5.0]
  LR_GROUP_REGEX: ["coss_.+","mlm_head.+","mim_head.+","mim_norm.+"]
DATASETS:
  TRAIN: ("PRW_TBPS_Train",) 
  TEST: ("PRW_TBPS_Gallery", "PRW_TBPS_Query",)
TEST:
  EVAL_PERIOD: 570
OUTPUT_DIR: "outputs/oim_clip/oim_simple_bi_mhml2dfullypred_prw_30_slr_open_b10_05mr_10lr_10mim" #_seed"
# SEED: 58216138