_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleDC2Bi"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 22824 # 951 * 24
  STEPS: (7608,) # 951 * 16
  CHECKPOINT_PERIOD: 1902
  WARMUP_ITERS: 951
  IMS_PER_BATCH: 12
DATASETS:
  TRAIN: ("PRW_TBPS_Train",) 
  TEST: ("PRW_TBPS_Gallery", "PRW_TBPS_Query",)
TEST:
  EVAL_PERIOD: 951
OUTPUT_DIR: "outputs/oim_clip/oim_simple_dc2_bi_prw_30_slr"