_BASE_: "base_tbps.yaml"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
SOLVER:
  MAX_ITER: 22800 # 1140 * 20
  STEPS: (18240,)
  CHECKPOINT_PERIOD: 1140
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 5
DATASETS:
  TRAIN: ("PRW_TBPS_Train",) 
  TEST: ("PRW_TBPS_Gallery", "PRW_TBPS_Query",)
TEST:
  EVAL_PERIOD: 4482
OUTPUT_DIR: "outputs/oim_clip/oim_prw"