_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleBi"
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 20520 # 570 * 36
  STEPS: (9120,) # 570 * 16
  CHECKPOINT_PERIOD: 1140
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 10
  LR_FACTORS: [5.0,5.0,]
  LR_GROUP_REGEX: ["proposal_generator.+","roi_heads.box_predictor.+",]
DATASETS:
  TRAIN: ("PRW_TBPS_Train",) 
  TEST: ("PRW_TBPS_Gallery", "PRW_TBPS_Query",)
TEST:
  IMS_PER_PROC: 8
  EVAL_PERIOD: 1140
OUTPUT_DIR: "outputs/oim_clip/oim_simple_bi_prw_30_slr_open_b10_plr_re"