_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimple"
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 44832 # 1868 * 24
  STEPS: (9340,)
  CHECKPOINT_PERIOD: 1868
  WARMUP_ITERS: 1868
  IMS_PER_BATCH: 12
DATASETS:
  TRAIN: ("CUHK-SYSU_TBPS_Train",) 
  TEST: ("CUHK-SYSU_TBPS_Gallery", "CUHK-SYSU_TBPS_TestG100",)
TEST:
  EVAL_PERIOD: 1868
OUTPUT_DIR: "outputs/oim_clip/oim_simple_cuhk_30_slr_open"