_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleBiMLM"
  ROI_HEADS:
    IOU_THRESHOLDS: [0.5]
    IOU_LABELS: [0, 1]
  ROI_BOX_HEAD:
      BBOX_REG_LOSS_WEIGHT: 10.0
      SMOOTH_L1_BETA: 1.0
      POOLER_SAMPLING_RATIO: 2
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  WEIGHT_DECAY: 1.0e-4
  MAX_ITER: 33600 # 1400 * 24
  STEPS: (14000,)
  CHECKPOINT_PERIOD: 2800
  WARMUP_ITERS: 1400
  IMS_PER_BATCH: 8
  LR_FACTORS: [5.0,5.0,5.0,5.0]
  LR_GROUP_REGEX: ["proposal_generator.+",".*box_predictor.+","coss_.+","mlm_head.+"]
DATASETS:
  TRAIN: ("CUHK-SYSU_TBPS_Train",) 
  TEST: ("CUHK-SYSU_TBPS_Gallery", "CUHK-SYSU_TBPS_TestG100",)
TEST:
  EVAL_PERIOD: 1400
OUTPUT_DIR: "outputs/oim_clip/oim_simple_bi_mlm_cuhk_30_slr_open_b8_0.5w_lbox_changelr"