_BASE_: "base_prompts.yaml"
MODEL:
  META_ARCHITECTURE: "PromptedSwinSimFPNLiteRCNNPSBoxAug"
  WEIGHTS: "outputs/swin_rcnn/simfpn-solider-l2pppMaskSeOrth-ps-prepend16-boxaug5_cuhk2prw_adam_b8_incoim_0wd_correctln_14x14/model_0024241.pth"
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[32], [64], [128], [256], [512]] # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    HEAD_NAME: "StandardRPNHead"
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000 # Per FPN level
    PRE_NMS_TOPK_TEST: 1000 # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 300
    CONV_DIMS: [-1,-1]
  ROI_HEADS:
    NAME: "StandardROIHeads" 
    NUM_CLASSES: 1
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    IOU_THRESHOLDS: [0.5]
    IOU_LABELS: [0, 1]
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
    SCORE_THRESH_TEST: 0.5
    NMS_THRESH_TEST: 0.4
    PROPOSAL_APPEND_GT: True
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1
    FC_DIM: 1024
    NUM_CONV: 4
    CONV_DIM: 256
    NORM: LN
    BBOX_REG_LOSS_TYPE: "smooth_l1"
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: [10.0, 10.0, 5.0, 5.0]
    SMOOTH_L1_BETA: 0.0
    POOLER_RESOLUTION: [14, 14]
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlignV2"
PERSON_SEARCH:
  QUERY_ENCODER_WEIGHTS: "Data/model_zoo/swin_rcnn_small_solider_d2.pkl"
  PROMPT:
    PROMPT_START_STAGE: 1
    NUM_PROMPTS: [4,4,4,4]
    POOL_SIZE: 12
    PROMPT_TYPE: "L2PppMaskSeOrth"
    NUM_TASKS: 3
    CURRENT_TASK: 2
    LOSS_WEIGHT: 0.1
    ORTH_MU: 100000
    TOP_K: 4
  DET:
    MODEL:
      TRANSFORMER:
        WITH_CP: True
        SEMANTIC_WEIGHT: 0.6
      SIM_FPN:
        IN_FEATURE: "side_stage3"
        OUT_CHANNELS: 256
        SCALE_FACTORS: [4.0, 2.0, 1.0, 0.5]
  REID:
    MODEL:
      IN_FEAT: "stage3"
      EMB_DIM: 768
      BN_NECK: False
    ID_ASSIGN:
      NAME: "det"
    BOX_AUGMENTATION:
      NAME: "dn_detr"
      H_CENTER: 0.4
      H_SCALE: 0.2
      NUM_LABELED: 4
      APPEND_GT: True
      NUM_UNLABLED: 4
    LOSS:
      INC_OIM:
        LB_LAYER: "lb_norm"
        ULB_LAYER: "ulb_full"
        LB_FACTOR: 30
        ULB_FACTOR: 30
        NUM_LB: [5532,483,2807]
        LEN_ULB: [5000,500,3000]
        FEAT_DIM: 768
        NORM_FEAT: True
        SYNC_MEMORY: True
        USE_FOCAL: True
        FOCAL_ALPHA: 1.0
        FOCAL_GAMMA: 2.0
        LOSS_WEIGHT: 1.0
SOLVER:
  OPTIM: "Adam"
  BASE_LR: 0.0003
  STEPS: (30240,60480)
  MAX_ITER: 63000 # 1260 * 50
  CHECKPOINT_PERIOD: 2520
  GAMMA: 0.1
  WEIGHT_DECAY: 0.0 # 5.0e-4
  IMS_PER_BATCH: 16
INPUT:
  MIN_SIZE_TRAIN: (160,192,224, 240)
  MAX_SIZE_TRAIN: 720
  MIN_SIZE_TEST_INC: [800,800,800,800,240,240]
  MAX_SIZE_TEST_INC: [1333,1333,1333,1333,720,720]
DATASETS:
  TRAIN: ("MovieNet_Train_app10",) 
  TEST: ("CUHK-SYSU_Gallery","CUHK-SYSU_TestG100","PRW_Gallery","PRW_Query","MovieNet_GalleryTestG2000","MovieNet_TestG2000",) #
TEST:
  IMS_PER_PROC: 3
  EVAL_PERIOD: 2520
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/simfpnlite-solider-l2pppMaskSeOrth-ps-prepend16-boxaug5_cuhk2prw2mvn_adam_b8_incoim_0wd_correctln_14x14"