_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VitPDPrompt"
  WEIGHTS: "Data/model_zoo/vit_small_cfs_lup.pkl"
  PATCH_EMBED:
    PRETRAIN_IMG_SIZE: [256,128]
PERSON_SEARCH:
  DET:
    MODEL:
      DO_NMS: True
      INIT_PE_SIZE: [800,1344]
      MID_PE_SIZE: [800,1344]
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LOSS_WEIGHT: 0.0
SOLVER:
  LR_SCHEDULER_NAME: "WarmupEpochBasedCosineLR"
  MAX_ITER: 576000 # 11520 * 50
  STEPS: (1,)
  BASE_LR: 1.0e-4
  CHECKPOINT_PERIOD: 11520
  WARMUP_ITERS: 0
  EPOCH_ITERS: 11520
  COS_LR_MAX_FACTOR: 1.0
  COS_LR_MIN_FACTOR: 0.01
DATASETS:
  TRAIN: ("COCO-P_DINO_Stochastic",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",)
TEST:
  EVAL_PERIOD: 11520
OUTPUT_DIR: "outputs/vit_ps/vitpd-prompt_coco_nms"