_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "Data/model_zoo/yolos_small_psd2.pkl"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
SOLVER:
  MAX_ITER: 140050 # 2801 * 50
  STEPS: (67224,134448)
  CHECKPOINT_PERIOD: 5602
  WARMUP_ITERS: 2801
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", "CUHK-SYSU_TestG100",) #
TEST:
  EVAL_PERIOD: 5602
OUTPUT_DIR: "outputs/vit_ps/vitps_cuhk"