_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VitPSPara"
  WEIGHTS: "Data/model_zoo/yolos_base_psd2.pkl"
  PATCH_EMBED:
    PRETRAIN_IMG_SIZE: [384,384]
    PATCH_SIZE: [16,16]
    EMBED_DIM: 768
PERSON_SEARCH:
  DET:
    MODEL:
      DO_NMS: True
      TRANSFORMER:
        DEPTH: 12
        NHEAD: 12
        MLP_RATIO: 4
        QKV_BIAS: True
        DROPOUT: 0.0
        DROP_PATH: 0.0
        ATTN_DROPOUT: 0.0
        DEIT: True
        INIT_PE_SIZE: [800,1344]
        MID_PE_SIZE: [800,1344]
  REID:
    MODEL:
        EMB_DIM: 768
        TRANSFORMER:
          DEPTH: 2
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
        FEAT_DIM: 768
SOLVER:
  LR_SCHEDULER_NAME: "WarmupEpochBasedCosineLR"
  MAX_ITER: 186750 # 3735 * 50
  STEPS: (1,)
  CHECKPOINT_PERIOD: 7470
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 3
  COS_LR_MAX_FACTOR: 1.0
  COS_LR_MIN_FACTOR: 0.01
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", "CUHK-SYSU_TestG100",) #
TEST:
  EVAL_PERIOD: 7470
OUTPUT_DIR: "outputs/vit_ps/vitps_cuhk_nms_vitbase_para2"