_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "Data/model_zoo/yolos_small_psd2.pkl"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LOSS_WEIGHT: 0.0
SOLVER:
  MAX_ITER: 71300 # 1426 * 50
  STEPS: (34224,68448)
  CHECKPOINT_PERIOD: 2852
  WARMUP_ITERS: 1426
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", "PRW_Query",) #
TEST:
  EVAL_PERIOD: 2852
OUTPUT_DIR: "outputs/vit_ps/vitps_prw_detonly"