_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VitPD"
  WEIGHTS: "Data/model_zoo/deit_small_p16_224.pkl"
PERSON_SEARCH:
  DET:
    MODEL:
      DO_NMS: True
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
        LOSS_WEIGHT: 0.0
SOLVER:
  LR_SCHEDULER_NAME: "WarmupEpochBasedCosineLR"
  MAX_ITER: 280100 # 2801 * 100
  STEPS: (1,)
  BASE_LR: 2.5e-5
  CHECKPOINT_PERIOD: 5602
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 4
  EPOCH_ITERS: 2801
  COS_LR_MAX_FACTOR: 1.0
  COS_LR_MIN_FACTOR: 0.004
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery",) #
TEST:
  EVAL_PERIOD: 5602
OUTPUT_DIR: "outputs/vit_ps/vitps_cuhk_detonly_cos_100_deit"