_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VitPSParaWithPrompts"
  WEIGHTS: "outputs/vit_ps_dino/vitps-small-dino_detpre_coco_lr-yolos_wd-yolos_clip-yolos/model_0203033.pth"
PERSON_SEARCH:
  NUM_PROMPTS: 256
  DET:
    MODEL:
      DO_NMS: True
  REID:
    MODEL:
      TRANSFORMER:
        DEPTH: 2
      BN_NECK: False
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
SOLVER:
  LR_SCHEDULER_NAME: "WarmupEpochBasedCosineLR"
  MAX_ITER: 71300 # 1426 * 50
  STEPS: (1,)
  CHECKPOINT_PERIOD: 2852
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 4
  COS_LR_MAX_FACTOR: 1.0
  COS_LR_MIN_FACTOR: 0.01
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", "PRW_Query",) #
TEST:
  EVAL_PERIOD: 3802
OUTPUT_DIR: "outputs/vit_ps/vitps-prompt_prw_nms_para2"