_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "VitPD"
  WEIGHTS: "Data/model_zoo/deit_small_p16_224.pkl"
PERSON_SEARCH:
  DET:
    MODEL:
      DO_NMS: True
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LOSS_WEIGHT: 0.0
SOLVER:
  LR_SCHEDULER_NAME: "WarmupEpochBasedCosineLR"
  MAX_ITER: 142600 # 1426 * 100
  STEPS: (1,)
  BASE_LR: 2.5e-5
  CHECKPOINT_PERIOD: 2852
  WARMUP_ITERS: 0
  EPOCH_ITERS: 1426
  COS_LR_MAX_FACTOR: 1.0
  COS_LR_MIN_FACTOR: 0.004
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery",) #
TEST:
  EVAL_PERIOD: 2852
OUTPUT_DIR: "outputs/vit_ps/vitps_prw_detonly_cos_100_deit"