_BASE_: "base.yaml"
MODEL:
  PATCH_TOKENIZER:
    STRIDES: [8,16,32]
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
SOLVER:
  MAX_ITER: 112050 # 2241 * 20
  STEPS: (89640,)
  CHECKPOINT_PERIOD: 2241
  WARMUP_ITERS: 2241
  IMS_PER_BATCH: 5
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ( "CUHK-SYSU_TestG100",) #"CUHK-SYSU_Gallery",
INPUT:
  SIZE_DIVISIBILITY: 32
TEST:
  EVAL_PERIOD: 4482
OUTPUT_DIR: "outputs/fpdtps/fpdtps_cuhk_32"