_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_backbone"
    FREEZE_AT: 2
  RESNETS:
    DEPTH: 50
    NORM: "FrozenBN"
    RES2_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    RES5_DILATION: 2
    OUT_FEATURES: ["res5"]
  ROI_HEADS:
    IN_FEATURES: ["res5"]
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
SOLVER:
  MAX_ITER: 112050 # 2241 * 20
  STEPS: (89640,)
  CHECKPOINT_PERIOD: 2241
  WARMUP_ITERS: 2241
  IMS_PER_BATCH: 5
  CLIP_GRADIENTS:
    CLIP_VALUE: 1.0
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", "CUHK-SYSU_TestG100",) #
TEST:
  EVAL_PERIOD: 4482
OUTPUT_DIR: "outputs/fpdtps/fpdtps_cuhk_resnet_d16_clip1"