MODEL:
  META_ARCHITECTURE: "SwinF4RCNN"
  WEIGHTS: "Data/model_zoo/swin_rcnn_small_solider_d2.pkl"
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  BACKBONE:
    NAME: "build_patch_embed_ln"
  PATCH_EMBED:
    PRETRAIN_IMG_SIZE: [256,128]
    PATCH_SIZE: [4,4]
    EMBED_DIM: 96
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[32, 64, 128, 256, 512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    HEAD_NAME: "StandardRPNHead" 
    IN_FEATURES: ["stage3"]
    IOU_THRESHOLDS: [0.3, 0.7]
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
    PRE_NMS_TOPK_TRAIN: 12000
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 300
    NMS_THRESH: 0.7
  ROI_HEADS:
    NUM_CLASSES: 1
    IN_FEATURES: ["stage3"]
    IOU_THRESHOLDS: [0.1, 0.5]
    IOU_LABELS: [0, -1, 1]
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
    SCORE_THRESH_TEST: 0.5
    NMS_THRESH_TEST: 0.4
    PROPOSAL_APPEND_GT: True
  ROI_BOX_HEAD:
      NAME: "" 
      BBOX_REG_LOSS_TYPE: "smooth_l1"
      BBOX_REG_LOSS_WEIGHT: 10.0
      BBOX_REG_WEIGHTS: [10.0, 10.0, 5.0, 5.0]
      SMOOTH_L1_BETA: 0.111111 # 0.0
      POOLER_RESOLUTION: [16, 8]
      POOLER_SAMPLING_RATIO: 2
      POOLER_TYPE: "ROIAlignV2"
PERSON_SEARCH:
  DET:
    NUM_CLASSES: 1
    MODEL:
      TRANSFORMER:
        DEPTH: [2,2,18,2]
        NHEAD: [3, 6, 12, 24]
        WIN_SIZE: 7
        MLP_RATIO: 4
        QKV_BIAS: True
        DROPOUT: 0.0
        DROP_PATH: 0.1
        ATTN_DROPOUT: 0.0
        SEMANTIC_WEIGHT: 0.6
        OUT_CHANNELS: 768
        WITH_CP: False
  REID:
    ID_ASSIGN:
      NAME: "det"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32

DATALOADER:
  NUM_WORKERS: 8
  ASPECT_RATIO_GROUPING: True

SOLVER:
  OPTIM: "SGD"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  WARMUP_ITERS: 0
  BASE_LR: 0.003
  WEIGHT_DECAY: 5.0e-4
  GAMMA: 0.1
  IMS_PER_BATCH: 4

TEST:
  IMS_PER_PROC: 4
  DETECTIONS_PER_IMAGE: 100
  DETECTION_SCORE_TS: [0.5,]
# SEED: 42
VIS_PERIOD: 1000
VERSION: 2