_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "SwinF4RCNNPS"
  WEIGHTS: "outputs/swin_rcnn/base-ps_prw/model_final.pth"
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        WITH_CP: True
  REID:
    MODEL:
      IN_FEAT: "stage3"
      EMB_DIM: 768
      BN_NECK: False
    ID_ASSIGN:
      NAME: "det"
    LOSS:
      OIM:
        LB_LAYER: "lb_norm"
        ULB_LAYER: "ulb_full"
        LB_FACTOR: 30
        ULB_FACTOR: 30
        NUM_LB: 5532
        LEN_ULB: 5000
        FEAT_DIM: 768
        NORM_FEAT: True
        SYNC_MEMORY: False
        USE_FOCAL: True
        FOCAL_ALPHA: 1.0
        FOCAL_GAMMA: 2.0
        LOSS_WEIGHT: 0.5
SOLVER:
  STEPS: (44832,89664)
  BASE_LR: 0.001
  MAX_ITER: 93400 # 1868 * 50
  CHECKPOINT_PERIOD: 3736
  GAMMA: 0.1
  IMS_PER_BATCH: 6
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 900)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("PRW_Gallery","PRW_Query","CUHK-SYSU_Gallery","CUHK-SYSU_TestG100") #
TEST:
  IMS_PER_PROC: 6
  EVAL_PERIOD: 3736
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/base-ps_prw2cuhk"