_BASE_: "base.yaml"
SOLVER:
  STEPS: (197800,395600)
  BASE_LR: 0.00003
  MAX_ITER: 494500 # 9890 * 50
  CHECKPOINT_PERIOD: 9890
  GAMMA: 0.1
  IMS_PER_BATCH: 8
DATASETS:
  TRAIN: ("COCO-CH",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",) #
TEST:
  EVAL_PERIOD: 19780
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/prompt_pd_cococh_slr"