_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "PromptedSwinF4RCNN"
  WEIGHTS: "outputs/swin_rcnn/prompt_pd_cococh/model_0356039.pth"
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        PROMPT_START_STAGE: 4
        NUM_PROMPTS: 64
        PROMPT_DROP_RATE: 0.0
SOLVER:
  OPTIM: "AdamW"
  LR_SCHEDULER_NAME: "WarmupEpochBasedCosineLR"
  STEPS: (1,)
  EPOCH_ITERS: 1426
  COS_LR_MAX_FACTOR: 1.0
  COS_LR_MIN_FACTOR: 0.01
  WARMUP_ITERS: 0
  BASE_LR: 0.0003
  MAX_ITER: 71300 # 1426 * 50
  CHECKPOINT_PERIOD: 1426
  GAMMA: 0.1
  IMS_PER_BATCH: 4
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 900)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery",) #
TEST:
  EVAL_PERIOD: 2852
  DETECTION_SCORE_TS: [0.5,]
SOLVER:

OUTPUT_DIR: "outputs/swin_rcnn/base-prompt-64_pd_prw_cococh-pretrain_adamw_coslr"