_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "Data/model_zoo/swin_small_patch4_window7_224_22k_d2.pkl"
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        SEMANTIC_WEIGHT: 0.0
        WITH_CP: False
SOLVER:
  STEPS: (197800,395600)
  BASE_LR: 0.0003
  MAX_ITER: 494500 # 9890 * 50
  CHECKPOINT_PERIOD: 9890
  GAMMA: 0.1
  IMS_PER_BATCH: 8
DATASETS:
  TRAIN: ("COCO-CH",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",) #
TEST:
  EVAL_PERIOD: 19780
  DETECTION_SCORE_TS: [0.5,]
VIS_PERIOD: 1
OUTPUT_DIR: "outputs/swin_rcnn/pd-pre_cococh_small-ign"