_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "Data/model_zoo/swin_rcnn_base_solider_d2.pkl"
  PATCH_EMBED:
    EMBED_DIM: 128
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        NHEAD: [4, 8, 16, 32]
        OUT_CHANNELS: 1024
SOLVER:
  STEPS: (197800,395600)
  BASE_LR: 0.0003
  MAX_ITER: 494500 # 9890 * 50
  CHECKPOINT_PERIOD: 9890
  GAMMA: 0.1
  IMS_PER_BATCH: 8
DATASETS:
  TRAIN: ("COCO-CH",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery",) #
TEST:
  EVAL_PERIOD: 19780
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/prompt_pd_cococh_swinbase"