_BASE_: "base_prompts.yaml"
MODEL:
  META_ARCHITECTURE: "PromptedSwinF4RCNNPSBoxAug"
  WEIGHTS: "outputs/swin_rcnn/ign-coda-ps-prepend16-boxaug4_cuhk2prw_adam_b8_incoim_0wd/model_final.pth"
PERSON_SEARCH:
  QUERY_ENCODER_WEIGHTS: "Data/model_zoo/swin_small_patch4_window7_224_22k_d2.pkl"
  PROMPT:
    PROMPT_START_STAGE: 1
    NUM_PROMPTS: [16,16,16,16]
    POOL_SIZE: 30
    PROMPT_TYPE: "CODAPrompt"
    NUM_TASKS: 3
    CURRECT_TASK: 2
    LOSS_WEIGHT: 0.1
  DET:
    MODEL:
      TRANSFORMER:
        WITH_CP: True
        SEMANTIC_WEIGHT: 0.0
  REID:
    MODEL:
      IN_FEAT: "stage3"
      EMB_DIM: 768
      BN_NECK: False
    ID_ASSIGN:
      NAME: "det"
    BOX_AUGMENTATION:
      NAME: "dn_detr"
      H_CENTER: 0.4
      H_SCALE: 0.2
      NUM_LABELED: 3
      APPEND_GT: True
      NUM_UNLABLED: 3
    LOSS:
      INC_OIM:
        LB_LAYER: "lb_norm"
        ULB_LAYER: "ulb_full"
        LB_FACTOR: 30
        ULB_FACTOR: 30
        NUM_LB: [5532,483,2087]
        LEN_ULB: [5000,500,3000]
        FEAT_DIM: 768
        NORM_FEAT: True
        SYNC_MEMORY: False
        USE_FOCAL: True
        FOCAL_ALPHA: 1.0
        FOCAL_GAMMA: 2.0
        LOSS_WEIGHT: 1.0
SOLVER:
  OPTIM: "Adam"
  BASE_LR: 0.0003
  STEPS: (30240,60480)
  MAX_ITER: 63000 # 1260 * 50
  CHECKPOINT_PERIOD: 2520
  GAMMA: 0.1
  WEIGHT_DECAY: 0.0 # 5.0e-4
  IMS_PER_BATCH: 16
INPUT:
  MIN_SIZE_TRAIN: (160,192,224, 240)
  MAX_SIZE_TRAIN: 720
  MIN_SIZE_TEST: 240
  MAX_SIZE_TEST: 720
DATASETS:
  TRAIN: ("MovieNet_Train_app10",) 
  TEST: ("CUHK-SYSU_Gallery","CUHK-SYSU_TestG100","PRW_Gallery","PRW_Query","MovieNet_GalleryTestG2000","MovieNet_TestG2000",) #
TEST:
  IMS_PER_PROC: 8
  EVAL_PERIOD: 2520
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/ign-coda-ps-prepend16-boxaug4_cuhk2prw2mvn_adam_b8_incoim_0wd"