_BASE_: "base_prompts.yaml"
MODEL:
  META_ARCHITECTURE: "PromptedSwinSimFPNRCNNPSBoxAug"
  WEIGHTS: "outputs/swin_rcnn/pd-pre-simfpn_cococh_small-ign/model_0336259.pth"
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[32], [64], [128], [256], [512]] # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    HEAD_NAME: "StandardRPNHead"
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000 # Per FPN level
    PRE_NMS_TOPK_TEST: 1000 # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 300
    CONV_DIMS: [-1,-1]
  ROI_HEADS:
    NAME: "StandardROIHeads" 
    NUM_CLASSES: 1
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    IOU_THRESHOLDS: [0.5]
    IOU_LABELS: [0, 1]
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
    SCORE_THRESH_TEST: 0.5
    NMS_THRESH_TEST: 0.4
    PROPOSAL_APPEND_GT: True
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1
    FC_DIM: 1024
    NUM_CONV: 4
    CONV_DIM: 256
    NORM: LN
    BBOX_REG_LOSS_TYPE: "smooth_l1"
    BBOX_REG_LOSS_WEIGHT: 10.0
    BBOX_REG_WEIGHTS: [10.0, 10.0, 5.0, 5.0]
    SMOOTH_L1_BETA: 0.0
    POOLER_RESOLUTION: [16, 8]
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlignV2"
PERSON_SEARCH:
  QUERY_ENCODER_WEIGHTS: "Data/model_zoo/swin_small_patch4_window7_224_22k_d2.pkl"
  PROMPT:
    PROMPT_START_STAGE: 1
    NUM_PROMPTS: [16,16,16,16]
    POOL_SIZE: 30
    PROMPT_TYPE: "CODAPrompt"
    NUM_TASKS: 3
    CURRECT_TASK: 0
    LOSS_WEIGHT: 0.1
  DET:
    MODEL:
      TRANSFORMER:
        WITH_CP: True
        SEMANTIC_WEIGHT: 0.0
      SIM_FPN:
        IN_FEATURE: "stage4"
        OUT_CHANNELS: 256
        SCALE_FACTORS: [4.0, 2.0, 1.0, 0.5]
  REID:
    MODEL:
      IN_FEAT: "stage3"
      EMB_DIM: 768
      BN_NECK: False
    ID_ASSIGN:
      NAME: "det"
    BOX_AUGMENTATION:
      NAME: "dn_detr"
      H_CENTER: 0.4
      H_SCALE: 0.2
      NUM_LABELED: 3
      APPEND_GT: True
      NUM_UNLABLED: 3
    LOSS:
      INC_OIM:
        LB_LAYER: "lb_norm"
        ULB_LAYER: "ulb_full"
        LB_FACTOR: 30
        ULB_FACTOR: 30
        NUM_LB: [5532,]
        LEN_ULB: [5000,]
        FEAT_DIM: 768
        NORM_FEAT: True
        SYNC_MEMORY: False
        USE_FOCAL: True
        FOCAL_ALPHA: 1.0
        FOCAL_GAMMA: 2.0
        LOSS_WEIGHT: 1.0
SOLVER:
  OPTIM: "Adam"
  BASE_LR: 0.0003
  STEPS: (33624,67248)
  MAX_ITER: 70050 # 1401 * 50
  CHECKPOINT_PERIOD: 2802
  GAMMA: 0.1
  WEIGHT_DECAY: 0.0 # 5.0e-4
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery","CUHK-SYSU_TestG100","CUHK-SYSU_GalleryGT","CUHK-SYSU_TestG100GT") #
TEST:
  IMS_PER_PROC: 6
  EVAL_PERIOD: 2802
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/simfpn-ign-coda-ps-prepend16-boxaug4_cuhk_adam_b8_incoim_0wd"