_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "MViTSimFPNRCNNLite"
  BACKBONE:
    NAME: "build_overlapped_patch_embed"
  PATCH_EMBED:
    PRETRAIN_IMG_SIZE: [224,224]
    KERNELS_SIZE: [7,7]
    STRIDE: [4,4]
    PADDING: [3,3]
    EMBED_DIM: 96
  WEIGHTS: "Data/model_zoo/MViTv2_B_in21k_d2.pth"
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[32], [64], [128], [256], [512]] # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    HEAD_NAME: "StandardRPNHead"
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000 # Per FPN level
    PRE_NMS_TOPK_TEST: 1000 # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 300
    CONV_DIMS: [-1,-1]
  ROI_HEADS:
    NAME: "StandardROIHeads" 
    NUM_CLASSES: 1
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    IOU_THRESHOLDS: [0.5]
    IOU_LABELS: [0, 1]
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
    SCORE_THRESH_TEST: 0.5
    NMS_THRESH_TEST: 0.4
    PROPOSAL_APPEND_GT: True
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1
    FC_DIM: 1024
    NUM_CONV: 4
    CONV_DIM: 256
    NORM: LN
    BBOX_REG_LOSS_TYPE: "smooth_l1"
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: [10.0, 10.0, 5.0, 5.0]
    SMOOTH_L1_BETA: 1.0
    POOLER_RESOLUTION: [16, 8]
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlignV2"
PERSON_SEARCH:
  DET:
    MODEL:
      TRANSFORMER:
        DEPTH: 24
        NHEAD: 1
        LAST_BLOCK_INDEXS: [1,4,20,23]
        QKV_POOL_KERNEL: [3,3]
        ADAPTIVE_KV_STRIDE: 4
        ADAPTIVE_WINDOW_SIZE: 56
        RESIDUAL_POOLING: True
        MLP_RATIO: 4
        QKV_BIAS: True
        DROP_PATH: 0.4
        WITH_CP: False
      SIM_FPN:
        IN_FEATURE: "stage3"
        OUT_CHANNELS: 256
        SCALE_FACTORS: [4.0, 2.0, 1.0, 0.5]

SOLVER:
  OPTIM: "AdamW"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  WARMUP_ITERS: 1000
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.01
  STEPS: (98900,197800)
  MAX_ITER: 247250 # 4945 * 50
  CHECKPOINT_PERIOD: 9890
  GAMMA: 0.1
  IMS_PER_BATCH: 16
DATASETS:
  TRAIN: ("COCO-CH",) 
  TEST: ("PRW_Gallery","CUHK-SYSU_Gallery","MovieNet_GalleryTestG2000") #
TEST:
  EVAL_PERIOD: 9890
  DETECTION_SCORE_TS: [0.5,]
OUTPUT_DIR: "outputs/swin_rcnn/pd-pre-simfpnlite_cococh_mvitbase-ign_lbox"