_BASE_: "base_prompts.yaml"
MODEL:
  META_ARCHITECTURE: "SwinLinearCDI"
  WEIGHTS: "Data/model_zoo/MixMAE_Swin-B-W14_600ep.pkl"
  PATCH_EMBED:
    PRETRAIN_IMG_SIZE: [224,224]
    EMBED_DIM: 128
PERSON_SEARCH:
  QUERY_ENCODER_WEIGHTS: "Data/model_zoo/MixMAE_Swin-B-W14_600ep.pkl"
  DOMAIN_IDENTIFY:
    DOMAIN_NAMES: ["CUHK-SYSU","PRW","MovieNet"]
  DET:
    MODEL:
      TRANSFORMER:
        WITH_CP: False
        SEMANTIC_WEIGHT: -1
        DEPTH: [2,2,18,2]
        NHEAD: [4, 8, 16, 32]
        WIN_SIZE: [14,14,14,7]
        MLP_RATIO: 4
        QKV_BIAS: True
        DROPOUT: 0.0
        DROP_PATH: 0.0
        ATTN_DROPOUT: 0.0
        OUT_CHANNELS: 1024
SOLVER:
  OPTIM: "Adam"
  BASE_LR: 0.0005
  STEPS: (33740,)
  MAX_ITER: 67480 # 1687 * 40
  CHECKPOINT_PERIOD: 3374
  GAMMA: 0.1
  WEIGHT_DECAY: 0.0 # 5.0e-4
  IMS_PER_BATCH: 16
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATASETS:
  TRAIN: ("CPM_Train",) 
  TEST: ("CUHK-SYSU_Gallery","PRW_Gallery","MovieNet_GalleryTestG2000") 
TEST:
  IMS_PER_PROC: 8
  EVAL_PERIOD: 1687

OUTPUT_DIR: "outputs/swin_rcnn/swin_linear_di_cpm_mixmae"