_BASE_: "base_prompts.yaml"
MODEL:
  META_ARCHITECTURE: "SwinMsCosCDI"
  WEIGHTS: "outputs/swin_rcnn/swin_ms_cos_cdi_cuhk2prw/model_final.pth"
PERSON_SEARCH:
  QUERY_ENCODER_WEIGHTS: "Data/model_zoo/swin_small_patch4_window7_224_22k_d2.pkl"
  DOMAIN_IDENTIFY:
    DOMAIN_NAMES: ["CUHK-SYSU","PRW","MovieNet"]
  DET:
    MODEL:
      TRANSFORMER:
        WITH_CP: False
        SEMANTIC_WEIGHT: -1
SOLVER:
  OPTIM: "Adam"
  BASE_LR: 0.0005
  STEPS: (6300,)
  MAX_ITER: 12600 # 630 * 20
  CHECKPOINT_PERIOD: 1260
  GAMMA: 0.1
  WEIGHT_DECAY: 0.0 # 5.0e-4
  IMS_PER_BATCH: 16
INPUT:
  MIN_SIZE_TRAIN: (160,192,224, 240)
  MAX_SIZE_TRAIN: 720
  MIN_SIZE_TEST: 240
  MAX_SIZE_TEST: 720
DATASETS:
  TRAIN: ("MovieNet_Train_app10",) 
  TEST: ("CUHK-SYSU_Gallery","PRW_Gallery","MovieNet_GalleryTestG2000") # ) 
TEST:
  IMS_PER_PROC: 16
  EVAL_PERIOD: 630

OUTPUT_DIR: "outputs/swin_rcnn/swin_ms_cos_cdi_cuhk2prw2mvn"