_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleDC2"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 25668 # 713 * 36
  STEPS: (14260,) # 713 * 20
  CHECKPOINT_PERIOD: 1426
  WARMUP_ITERS: 713
  IMS_PER_BATCH: 8
DATASETS:
  TRAIN: ("PRW_TBPS_Train",) 
  TEST: ("PRW_TBPS_Gallery", "PRW_TBPS_Query",)
TEST:
  IMS_PER_PROC: 4
  EVAL_PERIOD: 1426
OUTPUT_DIR: "outputs/oim_clip/oim_simple_dc2_prw_30_slr_b8"