_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleHybridBi"
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 26904 # 1121 * 24
  STEPS: (11210,)
  CHECKPOINT_PERIOD: 1121 #2242
  WARMUP_ITERS: 2242
  IMS_PER_BATCH: 10
DATASETS:
  TRAIN: ("CUHK-SYSU_TBPS_Train",) 
  TEST: ("CUHK-SYSU_TBPS_Gallery", "CUHK-SYSU_TBPS_TestG100",)
TEST:
  EVAL_PERIOD: 1120
SEED: 24847203
OUTPUT_DIR: "outputs/oim_clip/oim_simple_hbi_cuhk_30_slr_open_b10_seed"