_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipT2I"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
SOLVER:
  MAX_ITER: 44832 # 1868 * 24
  STEPS: (29888,)
  CHECKPOINT_PERIOD: 3736
  WARMUP_ITERS: 1868
  IMS_PER_BATCH: 6
DATASETS:
  TRAIN: ("CUHK-SYSU_TBPS_Train",) 
  TEST: ("CUHK-SYSU_TBPS_Gallery", "CUHK-SYSU_TBPS_TestG100",)
TEST:
  EVAL_PERIOD: 3736
OUTPUT_DIR: "outputs/oim_clip/oim_cuhk_t2i"