_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimple"
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 20520 # 570 * 36
  STEPS: (9120,) # 570 * 16
  CHECKPOINT_PERIOD: 1140
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 10
DATASETS:
  TRAIN: ("PRW_TBPS_Train",) 
  TEST: ("PRW_TBPS_Gallery",)
TEST:
  IMS_PER_PROC: 8
  EVAL_PERIOD: 1140
SEED: 58216138
OUTPUT_DIR: "outputs/oim_clip/oim_simple_prw_clip_feat"