_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleCombineBi"
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 13680 # 570 * 24
  STEPS: (6840,) # 570 * 12
  CHECKPOINT_PERIOD: 1140
  WARMUP_ITERS: 570
  IMS_PER_BATCH: 10
DATASETS:
  TRAIN: ("PRW_TBPS_Train",) 
  TEST: ("PRW_TBPS_Gallery", "PRW_TBPS_Query",)
TEST:
  IMS_PER_PROC: 8
  EVAL_PERIOD: 1140
SEED: 58216138
OUTPUT_DIR: "outputs/oim_clip/oim_simple_cbi_prw_30_slr_open_b10_seed"