_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimClipSimpleDC2"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 50400 # 1400 * 36
  STEPS: (28000,)
  CHECKPOINT_PERIOD: 2800
  WARMUP_ITERS: 1400
  IMS_PER_BATCH: 8
DATASETS:
  TRAIN: ("CUHK-SYSU_TBPS_Train",) 
  TEST: ("CUHK-SYSU_TBPS_Gallery", "CUHK-SYSU_TBPS_TestG100",)
TEST:
  EVAL_PERIOD: 2800
OUTPUT_DIR: "outputs/oim_clip/oim_simple_dc2_cuhk_30_slr_b8"