_BASE_: "base_tbps.yaml"
MODEL:
  META_ARCHITECTURE: "OimSeqClipSimpleBi"
  ROI_HEADS:
    IOU_THRESHOLDS: [ 0.5,]
    IOU_LABELS: [0, 1]
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 1.0
PERSON_SEARCH:
  DET:
    CLIP:
      FREEZE_AT_STAGE2: False
      FROZEN_BN: False
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
        LB_FACTOR: 30
        ULB_FACTOR: 30
SOLVER:
  BASE_LR: 0.00001
  MAX_ITER: 40320 # 1120 * 24
  STEPS: (11200,) # 1120 * 10
  CHECKPOINT_PERIOD: 2240
  WARMUP_ITERS: 1120
  IMS_PER_BATCH: 10
  LR_FACTORS: [10.0,10.0]
  LR_GROUP_REGEX: ["proposal_generator.+",".*box_predictor.+"]
DATASETS:
  TRAIN: ("CUHK-SYSU_TBPS_Train",) 
  TEST: ("CUHK-SYSU_TBPS_Gallery", "CUHK-SYSU_TBPS_TestG100",)
TEST:
  EVAL_PERIOD: 1868
OUTPUT_DIR: "outputs/oim_clip/oimseq_simple_bi_cuhk_30_slr_open_changelr2"