_BASE_: "base.yaml"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
SOLVER:
  MAX_ITER: 114000 # 1140 * 100
  STEPS: (91200,)
  CHECKPOINT_PERIOD: 5700
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 5
  CLIP_GRADIENTS:
    CLIP_VALUE: 1.0
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", "PRW_Query",) #
TEST:
  EVAL_PERIOD: 5700
OUTPUT_DIR: "outputs/plain_dtps/pdtps_prw_1clip"