_BASE_: "base.yaml"
PERSON_SEARCH:
  REID:
    LOSS:
      OIM:
        NUM_LB: 5532
        LEN_ULB: 5000
SOLVER:
  MAX_ITER: 224100 # 2241 * 20
  STEPS: (179280,)
  CHECKPOINT_PERIOD: 11205
  WARMUP_ITERS: 2241
  IMS_PER_BATCH: 5
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", "CUHK-SYSU_TestG100",) #
TEST:
  EVAL_PERIOD: 11205
OUTPUT_DIR: "outputs/plain_dtps/pdtps_cuhk"