_BASE_: "base.yaml"
MODEL:
  RESNETS:
    RES5_DILATION: 2
PERSON_SEARCH:
  REID:
    MODEL:
        TRANSFORMER:
          QUERY_POS: False
    LOSS:
      OIM:
        NUM_LB: 483
        LEN_ULB: 500
INPUT:
  SIZE_DIVISIBILITY: 16
SOLVER:
  MAX_ITER: 114000 # 1140 * 100
  STEPS: (91200,)
  CHECKPOINT_PERIOD: 5700
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 5
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", "PRW_Query",) #
TEST:
  EVAL_PERIOD: 5700
OUTPUT_DIR: "outputs/plain_dtps/pdtps_prw_d16_nqpos"