_BASE_: "clip_detr_baseline.yaml"
MODEL:
  META_ARCHITECTURE: "MQueryGrounding8Deform"
INPUT:
  MAX_QUERY_NUM: 8
SOLVER:
  BASE_LR: 0.0001
  MAX_ITER: 57000 # 570 * 100
  STEPS: (34200,) # 570 * 60
  CHECKPOINT_PERIOD: 5700
  WARMUP_ITERS: 1140
  IMS_PER_BATCH: 16
  FREEZE_PARAM_REGEX: ["clip.+",]
  LR_FACTORS: [5.0,5.0,5.0,5.0,5.0,5.0,5.0]
  LR_GROUP_REGEX: ["grounding_trans.+","ref_points.+","bbox_embed.+","conf_embed.+","query_embed.+","qimg.+","query_cls.+"]
DATASETS:
  TRAIN: ("PRW_Mmq_Train",) 
  # TEST: ("PRW_Mmq_Query","PRW_Mmq_Gallery",)
TEST:
  EVAL_PERIOD: 60000
OUTPUT_DIR: "outputs/mquery_gd/clip_8deform_llr_16query"
# SEED: 58216138