_BASE_: "clip_detr_baseline.yaml"
MODEL:
  META_ARCHITECTURE: "MQueryGrounding8DeformSplitCLS"
PERSON_SEARCH:
  REID:
    MODEL:
      RAND_MODAL: True
SOLVER:
  BASE_LR: 0.0001
  MAX_ITER: 42780 # 713 * 60
  STEPS: (28520,) # 713 * 40
  CHECKPOINT_PERIOD: 7130
  WARMUP_ITERS: 1426
  IMS_PER_BATCH: 8
  FREEZE_PARAM_REGEX: ["clip.+",]
  LR_FACTORS: [5.0,5.0,5.0,5.0,5.0,5.0,5.0]
  LR_GROUP_REGEX: ["grounding_trans.+","ref_points.+","bbox_embed.+","conf_embed.+","query_embed.+","qimg.+","query_cls.+"]
DATASETS:
  TRAIN: ("PRW_Mmq_Train",) 
  TEST: ("PRW_Mmq_Query","PRW_Mmq_Grounding",) # 
TEST:
  EVAL_PERIOD: 2852
OUTPUT_DIR: "outputs/mquery_gd/clip_8deform_rmodal_splitcls_1st_llr"
# SEED: 58216138